import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Source_Serif_4 } from "next/font/google";
import TanstackProvider from "@/provider/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { Loader2Icon } from "lucide-react";
export const metadata: Metadata = {
  title: "Booking Management System",
  description: "Generated by create next app",
};

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-source-serif",
  display: "swap",
});
//sdsdsd
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sourceSerif.variable} antialiased scroll-smooth`}
      suppressHydrationWarning
    >
      <head />
      <body className="overflow-x-hidden scroll-smooth!">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackProvider>
            <Suspense
              fallback={
                <main className="h-dvh w-dvw">
                  <Loader2Icon className={`animate-spin`} />
                </main>
              }
            >
              {children}
            </Suspense>
          </TanstackProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
